### ISSUE TITLE
CORS support for the Problem schema.yaml

### ISSUE THREAD

**Issue by languitar** [zalando/problem#236]
As already requested in [this rejected issue](https://github.com/zalando/zalando.github.io/issues/212), missing CORS support for the hosted version of `schema.yaml` prevents using this file in other projects.

## Description

Without CORS support on the host serving the file, any `$ref` to this file results in an error in the rendered Swagger UI, because the client is not allowed to fetch the reference.

## Expected Behavior

Any host is allowed to fetch this file.

## Actual Behavior

> Content Security Policy: The page’s settings blocked the loading of a resource at https://opensource.zalando.com/problem/schema.yaml (“connect-src”).

## Possible Fix

The hosting webserver needs to provide CORS headers (`access-control-allow-origin`).

## Steps to Reproduce

1. Create a custom OpenAPI specification using something such as the following:
    ```yaml
        '503':
          description: One or more upstream services are currently failing
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
    ```
2. Render a Swagger UI
3. Open the Swagger UI and open the Endpoint containing a response with the `$ref`
4. An error will appear
